spring:
  application:
    name: bookSystem
  datasource:
    url: jdbc:sqlite:src/main/resources/identifier.sqlite
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    show-sql: true  # 可选：显示生成的 SQL 语句
    hibernate:
      ddl-auto: update  # 根据需要选择策略（create, create-drop, validate, none）
  thymeleaf:
    enabled: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: UTF-8
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
